Add initial version for zwaad script readme/tutorial
snad-space/zwad pull request #120
Opened 2022-10-05 07:51 UTC by matwey

2022-10-05 07:52 UTC, matwey commented
There is also [aad_readme_before_pf](https://github.com/snad-space/zwad/tree/aad_readme_before_pf) branch for previous (pre-coniferest) zwaad version.

2022-10-05 15:09 UTC, hombit requested changes

2022-10-05 15:09 UTC, hombit commented on README.md
> +Check https://ztf.snad.space/dr4/view/695211400124577 for details
Should we say that instead of this line browser can be open? It is what happened to me

2022-10-05 15:09 UTC, hombit commented on README.md
> +```
After I run it I have the only new file `my_anomalies.txt`, no CSV file. And it is located in the current working directory, not in `data`

2022-10-05 15:21 UTC, hombit commented
Could you also check that you can reproduce this sequence of questions? In my case I have a different OIDs yielded.

2022-10-06 12:46 UTC, hombit approved these changes

2022-10-06 12:46 UTC, merged